### ISSUE TITLE
[Feature] negative scores

### ISSUE THREAD

**Issue by blauertee** [vatbub/Scoreboard#175]
I just downloaded the app and realized we can't play skat since you cannot enter negative points. I would be happy if that was possible. 

Thanks for this useful and lightweight app :)

**Comment by blauertee** [comment]
Nvm just didn't find it

**Comment by vatbub** [comment]
Yeah, depending on your keyboard, it's a little hidden. I also forgot about it and when I wanted to implement it, I realized that GBoard just has a negative-sign that looks like an underscore. If you have any other feedback, feel free to open more issues.
Cheers :)
